#!/bin/bash

if hash docker-compose 2>/dev/null; then
  docker exec -it $(docker ps | grep $1 | cut -d ' ' -f1) /bin/ash
else
  echo "docker-compose is required to run the Hodi platform." \
       "Visit https://docs.docker.com/compose/install/ for instructions."
fi
